name: web_widget
description: A web app that uses AngularDart Components
version: 1.3.3
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_bloc: ^4.0.0
  angular_router: ^2.0.0-alpha
  angular_forms: ^2.1.2
  angular_sentry: '^0.0.7'
  pedantic: ^1.8.0
  platform_detect: '^1.4.0'
  throttling: ^0.9.0
  angular_components: 0.13.0+1

  common_barkibu_dart:
    path: domain

dev_dependencies:
  angular_test: ^2.3.0
  built_html: ^0.1.4
  build_runner: ^1.7.0
  build_test: ^0.10.8
  build_web_compilers: ^2.10.0
  mockito: ^4.1.1
  pageloader: ^3.3.0
  sass_builder: ^2.1.2
  test: ^1.6.0

dependency_overrides:
  analyzer: ^0.36.0 # To resolve dependency conflict between pageloader and angular
  intl: 0.15.8 # To resolve common_barkibu_dart and angular
