name: Library CI
on:
  pull_request:
    branches: [develop]

jobs:
  tests:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:2.10

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
    - name: Run Dart Analyze
      run: PATH="$PATH:/usr/lib/dart/bin" dart analyze --fatal-infos
    - name: Run Dart Format Check
      run: PATH="$PATH:/usr/lib/dart/bin" find . -name "*.dart" \( -path "./lib/**" -o -path "./test/**" \) ! -name "*.g.dart" ! -name "*.chopper.dart" ! -name "*.i18n.dart" | xargs dart format -l 120 --fix -o none --set-exit-if-changed