name: common_barkibu_dart
description: A starting point for Dart libraries or applications.

version: 2.1.8

homepage: https://www.barkibu.com

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  json_annotation: 3.0.1
  json_serializable: <3.3.0
  chopper: 3.0.2
  bloc: 4.0.0
  equatable: ^1.2.3
  i18n: 0.9.10
  built_value: 7.0.9
  get_it: ^4.0.4
  pedantic: ^1.9.0
  intl: ^0.16.1
  amazon_cognito_identity_dart_2: ^0.1.17
  web_socket_channel: ^1.1.0
  uuid: 2.2.2
  time_machine:
    git:
      url: https://github.com/Dana-Ferguson/time_machine
      ref: 7753e0d
  seeip_client: ^0.1.2
  throttling: ^0.9.0
  merge_map: ^1.0.2

dev_dependencies:
  test: ^1.15.3
  mockito: ^4.1.1
  build_runner: 1.10.1
  chopper_generator: ^3.0.3
  built_value_generator: 7.0.7
  test_coverage: ^0.4.1
  built_collection: ^4.3.2
  dart_style: 1.3.6

dependency_overrides:
  analyzer: "^0.39.15"
